version: 0.2

phases:
  install:
    commands:
      # install Node 14
      - echo Installing Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
      #install Yarn
      - echo Installing Yarn...
      - npm install --global yarn
  pre_build:
    commands:
      #install dependencies
      - yarn
  build:
    commands:
      # test
      # build
      - echo Building React...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
